config/routes.rb
Rails.application.routes.draw do
  resources :branches
  resources :employees
  devise_for :users
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#homepage"
  get 'home/help'
  get 'home/docs'
end

app/models/branch.rb
class Branch < ApplicationRecord
    alias_attribute :branch, :branch_name
    has_many :employees

    def self.ransackable_attributes(auth_object= nil)
        %w(branch)
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_branch, only: %i[ show edit update destroy ]

  # GET /branches or /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1 or /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches or /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url(@branch), notice: "Branch was successfully created." }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_url(@branch), notice: "Branch was successfully updated." }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url, notice: "Branch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_params
      params.require(:branch).permit(:branch_name)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch.html.erb
<div id="<%= dom_id branch %>">
</div>

app/views/branches/_form.html.erb
<%= form_with(model: branch) do |form| %>
  <% if branch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>
      <ul>
        <% branch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :branch_name, style: "display: block" %>
    <%= form.text_field :branch_name, placeholder: "branch Name", class: "form-control mb-2" %>
  </div>
  <div class="b-example-divider"></div>
  <div class="form-group">
    <%= form.submit  class: "btn btn-primary btn-lg mt-3 mt-2" %>
    <%= link_to "Back", branches_path, class: "btn btn-lg mt3 mt-2" %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>
<%= render "form", branch: @branch %>
<br>
<div>
  <%= link_to "Show this branch", @branch %> |
  <%= link_to "Back to branches", branches_path %>
</div>

app/views/branches/index.html.erb
<div class="row mt-5">
  <div class="justify-content-md-center">
    <div class="row align-self-end">
      <div class="col-5"></div>
      <div class="col">
        <h2>BRANCH</h2>
      </div>
      <div class="col">
        <%= link_to "Add New Branch", new_branch_path, class: "btn btn-primary" if current_user %>
      </div>
    </div>
    <div class="row mt-4">
      <table class="table table-responsive table-striped table-hover text-center display compact" style="width: 50%; margin: 0 auto;" id="dttb-branches" data-sort="true" data-source="<%= url_for(format: :json)%>">
        <thead>
          <tr>
            <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px">ID</th>
            <th>Branch Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @branches.each do |branch| %>
            <tr class="">
              <td scope="row"><%= branch.id %></td>
              <td><%= branch.branch_name %></td>
              <% if current_user %>
                <td><%= link_to "Edit", edit_branch_path(branch), class: "btn btn-info btn-xs" %> | <%= link_to "Delete", branch, class: "btn btn-danger btn-xs" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/branches/new.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8 col-lg-6 col-xl-5">
    <h2 class="text-center">New Branch</h2>
    <div class="card py-4 px-5">
      <%= render "form", branch: @branch %>
    </div>
  </div>
</div>

app/views/branches/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @branch %>
<div>
  <%= link_to "Edit this branch", edit_branch_path(@branch) %> |
  <%= link_to "Back to branches", branches_path %>
  <%= button_to "Destroy this branch", @branch, method: :delete %>
</div>