config/routes.rb
Rails.application.routes.draw do
  resources :branches
  resources :employees
  devise_for :users
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#homepage"
  get 'home/help'
  get 'home/docs'
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :department
    belongs_to :branch

    validates :name, :department_id, :ext, :branch_id, presence: true

    def self.ransackable_attributes(auth_object= nil)
        %w(name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @q = Employee.ransack(params[:q])
    params[:company] = current_user ? Branch.ids : params[:company]
    @company = params[:company].nil? ? params[:q][:c]["0"][:v]["0"][:company] : params[:company]
    @pagy, @employees = pagy(@q.result(distinct: true).where(branch_id: @company), items: 12)
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url(@employee), notice: "Extension was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url(@employee), notice: "Extension was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Extension was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :department_id, :ext, :line_id, :branch_id)
    end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
    def company_name(id)
        if id == '3'
            "PT Bestari Mulia"
        elsif id == '4'
            "PT Anugerah Cemerlang Abadi"
        else
            "PT Royal Abadi Sejahtera"
        end
    end

    def line_number(line)
        if line != nil
            "(#{line})"
        else
            ""
        end
    end
end

app/views/employees/_employee.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Column 1</th>
        <th scope="col">Column 2</th>
        <th scope="col">Column 3</th>
      </tr>
    </thead>
    <tbody>
      <tr class="">
        <td scope="row">R1C1</td>
        <td>R1C2</td>
        <td>R1C3</td>
      </tr>
      <tr class="">
        <td scope="row">Item</td>
        <td>Item</td>
        <td>Item</td>
      </tr>
    </tbody>
  </table>
</div>


<div id="<%= dom_id employee %>">
  <p>
    <strong>Name:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= employee.department_id %>
  </p>

  <p>
    <strong>Ext:</strong>
    <%= employee.ext %>
  </p>

  <p>
    <strong>Line:</strong>
    <%= employee.line_id %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= simple_form_for @employee do |form| %>
  <div class="form-group">
    <%= form.input :name, placeholder: "Enter a Complete Name" %>
  </div>
  <div class="b-example-divider"></div>
  <div class="form-group">
    <%= form.association :branch, label_method: :branch_name, value_method: :id, prompt: "Select a Branch Name" %>
  </div>
  <div class="form-group">
    <%= form.association :department, prompt: "Select a Department Name",include_blank: false %>
  </div>
  <div class="b-example-divider"></div>
  <div class="form-group">
    <%= form.input :ext, placeholder: "Extention number" %>
  </div>
  <div class="b-example-divider"></div>
  <div class="form-group">
    <%= form.input :line_id, placeholder: "Line id number" %>
  </div>
  <div class="b-example-divider"></div>
  <div class="form-group">
    <%= form.submit  class: "btn btn-primary btn-lg mt-3 mt-2" %>
    <%= link_to "Back", employees_path, class: "btn btn-lg mt3 mt-2" %>
  </div>
<% end %>

app/views/employees/_search.html.erb
<div class="row justify-content-center">
  <div class="col-7 search-wrapper">
    <h1 class="text-center mb-4"><%= company_name(@company) %></h1>
    <%= search_form_for(@q, class: "d-flex") do |f| %>
      <%= f.grouping_fields(f.object.new_grouping) do |g| %>
        <%= f.condition_fields(g.object.new_condition) do |c| %>
          <div class="col">
            <%= c.attribute_fields do |a| %>
              <%= a.attribute_select({associations: [:department, :branch], selected: (params[:q].nil? ? "name" : params[:q][:c]["0"][:a]["0"][:name])}, {class: "form-select me-2"}) %>
            <% end %>
          </div>
          <div class="col">
            <%= c.predicate_select({only: %i(cont)} , {class: "form-select me-2"})  %>
          </div>
          <div class="custom-search">
            <%= c.value_fields do |v| %>
              <%= v.hidden_field :company, value: @company %>
              <%= v.text_field :value, value: (params[:q].nil? ? "" : params[:q][:c]["0"][:v]["0"][:value]), placeholder: "Type Here to Search", 
                            class: "custom-search-input" %>
            <% end %><button id="reset_button" class="btn custom-search-botton" type="button"><i class="bi bi-x"></i></button>
          </div>
        <% end %>
      <% end %>
      <div class="col-1 ms-1">
        <%= f.submit "Search", class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8 col-lg-6 col-xl-5">
    <h2 class="text-center">Edit Extention</h2>
    <div class="card py-4 px-5">
      <%= render "form", employee: @employee %>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="justify-content-md-center">
    <div class= "mx-auto mb-5 mt-5">
      <%= render "employees/search" %>
    </div>
    <div class="row align-self-end">
      <div class="col-8"></div>
      <div class="col"></div>
      <div class="col">
        <%= link_to raw("<i class=\"bi bi-plus-circle\"> Add Extention</i>"), new_employee_path, class: "btn btn-primary" if current_user %>
      </div>
    </div>
    <div class="table table-responsive text-center">
      <table class="col-4 table table-striped table-hover text-center">
        <thead>
          <tr>
            <th scope="col">Company</th>
            <th scope="col">Name</th>
            <th scope="col">Department</th>
            <th scope="col">Extention <i class="bi bi-patch-question-fill" id="test" data-bs-toggle="popover" title="Apa arti (9) dan (7)?" 
              data-bs-content="Jika anda menggunakan extension dengan line id 7, maka tekan 9 dilanjutkan nomor extension. Berlaku juga sebaliknya."></i></th>
            <% if current_user %>
              <th scope="col">Actions</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr class="">
              <td scope="row"><%= employee.branch.branch_name %></td>
              <td><%= employee.name.titleize %></td>
              <td><%= employee.department.name %></td>
              <td><%= line_number(employee.line_id)%><%= employee.ext %></td>
              <% if current_user %>
                <td><%= link_to "Edit", edit_employee_path(employee), class: "btn btn-info btn-xs" %> | 
                <%= button_to "Delete", employee, method: :delete, data: {
                    turbo_method: :delete,  
                    turbo_confirm: "Are you sure?"
                  }, form: {style: 'display:inline-block;'}, class: "btn btn-danger btn-xs" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-end">
        <%== pagy_bootstrap_nav @pagy %>
      </div>
    </div>
  </div>

app/views/employees/new.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8 col-lg-6 col-xl-5">
    <h2 class="text-center">New Extention</h2>
    <div class="card py-4 px-5">
      <%= render "form", employee: @employee %>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>