config/routes.rb
Rails.application.routes.draw do
  resources :branches
  resources :employees
  devise_for :users
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#homepage"
  get 'home/help'
  get 'home/docs'
end

app/models/department.rb
class Department < ApplicationRecord
    alias_attribute :dept_name, :name
    has_many :employees

    validates :name, presence: true, uniqueness: true

    def self.ransackable_attributes(auth_object= nil)
        %w(dept_name)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @q = Department.ransack(params[:q])
    @pagy, @departments = pagy(@q.result(distinct: true), items: 10)
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= simple_form_for @department do |form| %>
  <div class="form-group">
    <%= form.input :name, placeholder: "Department Name" %>
  </div>
  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg mt-3 mt-2" %>
    <%= link_to "Back", departments_path, class: "btn btn-lg mt3 mt-2" %>
  </div>
<% end %>

app/views/departments/_search.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <%= search_form_for(@q, class: "d-flex") do |f| %>
      <%= f.search_field :dept_name_cont, 
                                placeholder: "Type Here to Search", 
                                class: "form-control me-2" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/departments/edit.html.erb
<div class="row d-flex justify-content-center mt-5">
  <div class="col-12 col-md-8 col-lg-6 col-xl-5">
    <h2 class="text-center">Edit Department</h2>
    <div class="card py-3 px-2">
      <%= render "form", department: @department %>
    </div>
  </div>
</div>

app/views/departments/index.html.erb
<div class="row">
  <div class="justify-content-md-center">
    <div class= "mx-auto mb-5 mt-5">
      <%= render "departments/search" %>
    </div>
    <div class="row align-self-end">
      <div class="col-8"></div>
      <div class="col"></div>
      <div class="col">
        <%= link_to raw("<i class=\"bi bi-plus-circle\"> Add Department</i>"), new_department_path, class: "btn btn-primary" if current_user %>
      </div>
    </div>
    <div class="table table-responsive text-center">
      <table class="col-4 table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Department<i class="fa-solid fa-a"></i></th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @departments.each do |dept| %>
            <tr class="">
              <td scope="row"><%= dept.name %></td>
              <td><%= link_to "Edit", edit_department_path(dept), class: "btn btn-info btn-xs" %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-end">
        <%== pagy_bootstrap_nav @pagy %>
      </div>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class="row d-flex justify-content-center mt-5">
  <div class="col-12 col-md-8 col-lg-6 col-xl-5">
    <h2 class="text-center">New department</h2>
    <div class="card py-3 px-2">
      <%= render "form", department: @department %>
    </div>
  </div>
</div>

app/views/departments/show.html.erb
<%= render @department %>
<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>
  <%= button_to "Destroy this department", @department, method: :delete %>
</div>